import type { UserGroup } from "./types"

export interface SignalTemplate {
  id: string
  name: string
  description: string
  team: UserGroup
  connected: boolean
  dataSource: string
  explanation?: string
  whyItMatters?: string
}

export const signalTemplates: SignalTemplate[] = [
  // Sales Signals
  {
    id: "win-loss",
    name: "Win/Loss Rate",
    description: "Track the percentage of deals won vs lost",
    team: "sales",
    connected: false,
    dataSource: "Salesforce",
    explanation: "Calculated by dividing won deals by total closed deals (won + lost)",
    whyItMatters: "Shows sales effectiveness and helps identify what's working in your sales process",
  },
  {
    id: "pipeline-coverage",
    name: "Pipeline Coverage",
    description: "Ratio of pipeline value to quota",
    team: "sales",
    connected: false,
    dataSource: "HubSpot",
    explanation: "Total pipeline value divided by sales quota",
    whyItMatters: "Indicates whether you have enough pipeline to hit targets",
  },
  {
    id: "quota-attainment",
    name: "Quota Attainment",
    description: "Percentage of sales quota achieved",
    team: "sales",
    connected: false,
    dataSource: "Salesforce",
    explanation: "Actual revenue divided by quota target",
    whyItMatters: "Core metric for sales performance and forecasting",
  },
  {
    id: "deal-velocity",
    name: "Deal Velocity",
    description: "Average time from lead to closed deal",
    team: "sales",
    connected: false,
    dataSource: "HubSpot",
    explanation: "Average days between deal creation and closing",
    whyItMatters: "Faster velocity means more efficient sales process",
  },
  {
    id: "deal-score",
    name: "Deal Score",
    description: "Likelihood of deal closing",
    team: "sales",
    connected: false,
    dataSource: "Gong",
    explanation: "AI-powered score based on deal activity and signals",
    whyItMatters: "Helps prioritize which deals to focus on",
  },
  {
    id: "intent-signals",
    name: "Intent Signals",
    description: "Buyer intent indicators",
    team: "sales",
    connected: false,
    dataSource: "Gong",
    explanation: "Engagement patterns indicating purchase intent",
    whyItMatters: "Identifies hot prospects for prioritization",
  },
  {
    id: "activity-response",
    name: "Activity Response Rate",
    description: "Response rate to outreach",
    team: "sales",
    connected: false,
    dataSource: "Salesforce",
    explanation: "Percentage of outreach activities that get responses",
    whyItMatters: "Measures effectiveness of sales motions",
  },

  // Marketing Signals
  {
    id: "cac",
    name: "Customer Acquisition Cost (CAC)",
    description: "Cost to acquire a new customer",
    team: "marketing",
    connected: false,
    dataSource: "HubSpot",
    explanation: "Total marketing spend divided by new customers acquired",
    whyItMatters: "Essential for understanding marketing ROI and unit economics",
  },
  {
    id: "roas",
    name: "Return on Ad Spend (ROAS)",
    description: "Revenue generated per dollar spent on advertising",
    team: "marketing",
    connected: false,
    dataSource: "Meta Ads",
    explanation: "Revenue from ads divided by ad spend",
    whyItMatters: "Measures advertising effectiveness and campaign ROI",
  },
  {
    id: "mql-volume",
    name: "MQL Volume",
    description: "Number of marketing qualified leads",
    team: "marketing",
    connected: false,
    dataSource: "HubSpot",
    explanation: "Total leads meeting qualification criteria",
    whyItMatters: "Measures top-of-funnel marketing effectiveness",
  },
  {
    id: "traffic",
    name: "Website Traffic",
    description: "Visitors to your website",
    team: "marketing",
    connected: false,
    dataSource: "Google Analytics",
    explanation: "Unique visitors and page views over time",
    whyItMatters: "Indicates brand awareness and content effectiveness",
  },
  {
    id: "conversion-rate",
    name: "Conversion Rate",
    description: "Percentage of visitors who convert",
    team: "marketing",
    connected: false,
    dataSource: "Google Analytics",
    explanation: "Conversions divided by total visitors",
    whyItMatters: "Shows effectiveness of marketing funnel and messaging",
  },

  // Product Signals
  {
    id: "retention",
    name: "Retention Rate",
    description: "Percentage of users who return",
    team: "product",
    connected: false,
    dataSource: "Amplitude",
    explanation: "Users active in period N who were active in period N-1",
    whyItMatters: "Core indicator of product value and engagement",
  },
  {
    id: "activation",
    name: "Activation Rate",
    description: "Percentage of users who complete key actions",
    team: "product",
    connected: false,
    dataSource: "Mixpanel",
    explanation: "Users who complete activation milestones",
    whyItMatters: "Predicts long-term retention and product-market fit",
  },
  {
    id: "adoption",
    name: "Feature Adoption",
    description: "Percentage of users using key features",
    team: "product",
    connected: false,
    dataSource: "Amplitude",
    explanation: "Users who engage with feature divided by total users",
    whyItMatters: "Validates product decisions and guides roadmap",
  },
  {
    id: "nps",
    name: "Net Promoter Score",
    description: "Customer satisfaction and loyalty metric",
    team: "product",
    connected: false,
    dataSource: "Zendesk",
    explanation: "Percentage of promoters minus percentage of detractors",
    whyItMatters: "Predicts customer retention and word-of-mouth growth",
  },
  {
    id: "csat",
    name: "Customer Satisfaction (CSAT)",
    description: "Customer satisfaction score",
    team: "product",
    connected: false,
    dataSource: "Productboard",
    explanation: "Average satisfaction rating from customer surveys",
    whyItMatters: "Direct measure of product quality and user happiness",
  },
  {
    id: "arr-impact",
    name: "ARR Impact",
    description: "Annual recurring revenue impact",
    team: "product",
    connected: false,
    dataSource: "Looker",
    explanation: "Revenue attributed to product changes",
    whyItMatters: "Shows financial impact of product decisions",
  },
  {
    id: "cohort-analysis",
    name: "Cohort Analysis",
    description: "User behavior by cohort",
    team: "product",
    connected: false,
    dataSource: "Amplitude",
    explanation: "Retention and engagement patterns by user cohort",
    whyItMatters: "Identifies which user segments are most valuable",
  },
  {
    id: "funnel-metrics",
    name: "Funnel Conversion Metrics",
    description: "Step-by-step conversion rates",
    team: "product",
    connected: false,
    dataSource: "Mixpanel",
    explanation: "Conversion rates at each funnel step",
    whyItMatters: "Identifies where users drop off",
  },
  {
    id: "model-accuracy",
    name: "Model Accuracy",
    description: "ML model prediction accuracy",
    team: "product",
    connected: false,
    dataSource: "Databricks",
    explanation: "Percentage of correct predictions",
    whyItMatters: "Validates model performance",
  },
  {
    id: "prediction-lift",
    name: "Prediction Lift",
    description: "Model improvement over baseline",
    team: "product",
    connected: false,
    dataSource: "BigQuery",
    explanation: "Performance gain from ML predictions",
    whyItMatters: "Shows value of predictive models",
  },

  // Engineering Signals
  {
    id: "velocity",
    name: "Sprint Velocity",
    description: "Story points completed per sprint",
    team: "engineering",
    connected: false,
    dataSource: "Jira",
    explanation: "Sum of completed story points in sprint",
    whyItMatters: "Helps with sprint planning and capacity forecasting",
  },
  {
    id: "cycle-time",
    name: "Cycle Time",
    description: "Time from start to done",
    team: "engineering",
    connected: false,
    dataSource: "Linear",
    explanation: "Average time from first commit to production deploy",
    whyItMatters: "Measures development efficiency and delivery speed",
  },
  {
    id: "bug-count",
    name: "Bug Count",
    description: "Number of open bugs",
    team: "engineering",
    connected: false,
    dataSource: "Jira",
    explanation: "Total bugs in backlog and in progress",
    whyItMatters: "Indicates code quality and technical debt",
  },
  {
    id: "deployment-freq",
    name: "Deployment Frequency",
    description: "How often code is deployed",
    team: "engineering",
    connected: false,
    dataSource: "GitHub",
    explanation: "Number of production deployments per time period",
    whyItMatters: "Key DevOps metric for delivery velocity",
  },
  {
    id: "incident-rate",
    name: "Incident Rate",
    description: "Number of production incidents",
    team: "engineering",
    connected: false,
    dataSource: "PagerDuty",
    explanation: "Critical incidents requiring immediate attention",
    whyItMatters: "Measures system reliability and stability",
  },
  {
    id: "system-reliability",
    name: "System Reliability (Uptime)",
    description: "Percentage of time systems are operational",
    team: "engineering",
    connected: false,
    dataSource: "Datadog",
    explanation: "Uptime percentage over time period",
    whyItMatters: "Critical for customer trust and SLA compliance",
  },
  {
    id: "on-call-load",
    name: "On-Call Load",
    description: "Pages and incidents during on-call",
    team: "engineering",
    connected: false,
    dataSource: "PagerDuty",
    explanation: "Number of pages per on-call shift",
    whyItMatters: "Indicates system stability and team health",
  },

  // Design Signals
  {
    id: "task-completion",
    name: "Task Completion Rate",
    description: "Percentage of users completing tasks",
    team: "design",
    connected: false,
    dataSource: "Hotjar",
    explanation: "Users who successfully complete target tasks",
    whyItMatters: "Measures UX effectiveness and usability",
  },
  {
    id: "usability-score",
    name: "Usability Score",
    description: "User satisfaction with interface",
    team: "design",
    connected: false,
    dataSource: "UserTesting",
    explanation: "Average usability rating from user tests",
    whyItMatters: "Validates design decisions and identifies friction",
  },
  {
    id: "drop-off-rate",
    name: "Drop-off Rate",
    description: "Where users abandon flows",
    team: "design",
    connected: false,
    dataSource: "Maze",
    explanation: "Percentage of users leaving at each step",
    whyItMatters: "Identifies UX problems and optimization opportunities",
  },
  {
    id: "design-system-usage",
    name: "Design System Adoption",
    description: "Usage of design system components",
    team: "design",
    connected: false,
    dataSource: "Figma",
    explanation: "Percentage of designs using system components",
    whyItMatters: "Ensures consistency and speeds up development",
  },
  {
    id: "heatmaps",
    name: "Heatmap Analysis",
    description: "User click and scroll patterns",
    team: "design",
    connected: false,
    dataSource: "Hotjar",
    explanation: "Visual representation of user interactions",
    whyItMatters: "Shows what users focus on and ignore",
  },
  {
    id: "sus-score",
    name: "SUS Score",
    description: "System Usability Scale score",
    team: "design",
    connected: false,
    dataSource: "UserTesting",
    explanation: "Standardized usability questionnaire score",
    whyItMatters: "Benchmarks usability against industry standards",
  },
  {
    id: "thematic-patterns",
    name: "Thematic Patterns",
    description: "Recurring themes in user research",
    team: "design",
    connected: false,
    dataSource: "Dovetail",
    explanation: "Common patterns from qualitative research",
    whyItMatters: "Identifies key user pain points and desires",
  },
  {
    id: "time-to-task",
    name: "Time to Task Completion",
    description: "How long tasks take users",
    team: "design",
    connected: false,
    dataSource: "Maze",
    explanation: "Average time to complete key tasks",
    whyItMatters: "Measures efficiency of user flows",
  },

  // Customer Success Signals
  {
    id: "health-score",
    name: "Account Health Score",
    description: "Overall account health metric",
    team: "customer-success",
    connected: false,
    dataSource: "Gainsight",
    explanation: "Composite score based on usage, support, and engagement",
    whyItMatters: "Predicts churn risk and expansion opportunities",
  },
  {
    id: "usage-frequency",
    name: "Usage Frequency",
    description: "How often customers use product",
    team: "customer-success",
    connected: false,
    dataSource: "Amplitude",
    explanation: "Average sessions per user per time period",
    whyItMatters: "Indicates product stickiness and value",
  },
  {
    id: "support-volume",
    name: "Support Ticket Volume",
    description: "Number of support requests",
    team: "customer-success",
    connected: false,
    dataSource: "Zendesk",
    explanation: "Total support tickets opened in period",
    whyItMatters: "Indicates product issues and customer satisfaction",
  },
  {
    id: "cs-nps",
    name: "NPS (Customer Success)",
    description: "Customer loyalty score",
    team: "customer-success",
    connected: false,
    dataSource: "Gainsight",
    explanation: "Net Promoter Score from customer surveys",
    whyItMatters: "Predicts retention and referrals",
  },

  // Finance Signals
  {
    id: "burn-rate",
    name: "Burn Rate",
    description: "Monthly cash spend",
    team: "finance",
    connected: false,
    dataSource: "Netsuite",
    explanation: "Net cash decrease per month",
    whyItMatters: "Critical for runway and fundraising planning",
  },
  {
    id: "runway",
    name: "Runway",
    description: "Months of cash remaining",
    team: "finance",
    connected: false,
    dataSource: "Xero",
    explanation: "Cash balance divided by monthly burn",
    whyItMatters: "Determines when you need to raise or become profitable",
  },
  {
    id: "margins",
    name: "Gross Margin",
    description: "Profit margin percentage",
    team: "finance",
    connected: false,
    dataSource: "Netsuite",
    explanation: "Revenue minus COGS divided by revenue",
    whyItMatters: "Indicates business model efficiency and scalability",
  },
  {
    id: "forecast-accuracy",
    name: "Forecast Accuracy",
    description: "How accurate financial forecasts are",
    team: "finance",
    connected: false,
    dataSource: "Stripe",
    explanation: "Actual revenue vs forecasted revenue",
    whyItMatters: "Improves planning and stakeholder confidence",
  },
  {
    id: "revenue-growth",
    name: "Revenue Growth",
    description: "Month-over-month revenue growth",
    team: "finance",
    connected: false,
    dataSource: "Netsuite",
    explanation: "Percentage increase in revenue",
    whyItMatters: "Core metric for business health",
  },
  {
    id: "gtm-efficiency",
    name: "GTM Efficiency",
    description: "Go-to-market efficiency ratio",
    team: "finance",
    connected: false,
    dataSource: "Looker",
    explanation: "New ARR divided by sales & marketing spend",
    whyItMatters: "Measures efficiency of growth investments",
  },

  // Delivery Signals
  {
    id: "delivery-velocity",
    name: "Delivery Velocity",
    description: "Work completed per sprint",
    team: "delivery",
    connected: false,
    dataSource: "Jira",
    explanation: "Story points or tickets completed",
    whyItMatters: "Helps plan capacity and set expectations",
  },
  {
    id: "wip",
    name: "Work in Progress",
    description: "Number of concurrent tasks",
    team: "delivery",
    connected: false,
    dataSource: "Linear",
    explanation: "Items currently being worked on",
    whyItMatters: "Too much WIP reduces efficiency and increases cycle time",
  },
  {
    id: "burndown",
    name: "Sprint Burndown",
    description: "Work remaining in sprint",
    team: "delivery",
    connected: false,
    dataSource: "Jira",
    explanation: "Story points remaining vs ideal burndown",
    whyItMatters: "Tracks sprint progress and identifies risks early",
  },
  {
    id: "dependency-status",
    name: "Dependency Status",
    description: "Blocked work items",
    team: "delivery",
    connected: false,
    dataSource: "Notion",
    explanation: "Tasks blocked by dependencies",
    whyItMatters: "Identifies bottlenecks and coordination issues",
  },
]

export function getSignalById(signalId: string): SignalTemplate | undefined {
  return signalTemplates.find((s) => s.id === signalId)
}

export function getSignalsByTeam(team: UserGroup): SignalTemplate[] {
  return signalTemplates.filter((s) => s.team === team)
}
